import { Product, Collection, Review } from "@/types";
import { IMAGE_ASSETS } from "./imageAssets";

export const COLLECTIONS: Collection[] = [
  {
    id: "col-diamond",
    title: "Diamond",
    category: "diamond",
    image: IMAGE_ASSETS.collections.diamond.url,
    alt: IMAGE_ASSETS.collections.diamond.alt,
    description: "Brilliance in every facet. Solitaires, baguettes, and fine pavé settings.",
    itemCount: 24,
  },
  {
    id: "col-gold",
    title: "Gold",
    category: "gold",
    image: IMAGE_ASSETS.collections.gold.url,
    alt: IMAGE_ASSETS.collections.gold.alt,
    description: "Solid 18K and 22K gold heirlooms, sculptured with everlasting warmth.",
    itemCount: 38,
  },
  {
    id: "col-silver",
    title: "Silver",
    category: "silver",
    image: IMAGE_ASSETS.collections.silver.url,
    alt: IMAGE_ASSETS.collections.silver.alt,
    description: "925 sterling silver minimalist luxury for modern silhouettes.",
    itemCount: 19,
  },
  {
    id: "col-traditional",
    title: "Traditional",
    category: "traditional",
    image: IMAGE_ASSETS.collections.traditional.url,
    alt: IMAGE_ASSETS.collections.traditional.alt,
    description: "Royal Jadau, Polki, and antique temple ornaments steeped in culture.",
    itemCount: 32,
  },
  {
    id: "col-bridal",
    title: "Bridal",
    category: "bridal",
    image: IMAGE_ASSETS.collections.bridal.url,
    alt: IMAGE_ASSETS.collections.bridal.alt,
    description: "Bespoke bridal suites for life's most unforgettable milestone.",
    itemCount: 15,
  },
];

export const PRODUCTS: Product[] = [
  // 1. Royal Bloom Diamond Ring (Featured & New Arrival)
  {
    id: "prod-1",
    name: "Royal Bloom Diamond Ring",
    subtitle: "18K White Gold Solitaire with Pavé Halo",
    description: "A testament to celestial craftsmanship. The Royal Bloom Diamond Ring features a hand-selected 1.50ct round brilliant centre diamond embraced by a shimmering pavé halo on an 18K white gold micro-set band.",
    details: [
      "Certified IGI / GIA Natural Diamond",
      "1.50 Carat Centre Stone (VVS1 Clarity, E Color)",
      "Band crafted in Hallmarked 18K White Gold",
      "Complimentary laser engraving & luxury presentation chest",
      "Lifetime cleaning & inspection guarantee",
    ],
    price: 185000,
    originalPrice: 215000,
    discountPercentage: 14,
    category: "diamond",
    metal: "18K White Gold",
    stone: "Solitaire Diamond",
    stock: 5,
    rating: 4.9,
    reviewCount: 38,
    images: [
      IMAGE_ASSETS.newArrivals.royalBloomDiamondRing.url,
      IMAGE_ASSETS.productDetailMain.url,
      IMAGE_ASSETS.collections.diamond.url,
    ],
    isNewArrival: true,
    isFeatured: true,
    isBestSeller: true,
    sizes: ["US 5", "US 6", "US 7", "US 8", "US 9"],
    purity: "18K (750 Gold)",
    sku: "LUX-RBD-01",
  },

  // 2. Golden Grace Necklace
  {
    id: "prod-2",
    name: "Golden Grace Necklace",
    subtitle: "22K Sculpted Yellow Gold Collar Chain",
    description: "Fluid geometry in warm 22K yellow gold. Inspired by timeless Byzantine link architecture, this necklace drapes like liquid light against the collarbone.",
    details: [
      "Hallmarked 22K (916) Pure Yellow Gold",
      "Net Weight: 34.5 grams",
      "Secure custom toggle clasp with safety lock",
      "Hand-polished mirror and satin contrast finish",
    ],
    price: 245000,
    originalPrice: 270000,
    discountPercentage: 9,
    category: "gold",
    metal: "22K Yellow Gold",
    stone: "None",
    stock: 3,
    rating: 4.8,
    reviewCount: 22,
    images: [
      IMAGE_ASSETS.newArrivals.goldenGraceNecklace.url,
      IMAGE_ASSETS.collections.gold.url,
      IMAGE_ASSETS.shopProducts.floralDiamondBracelet.url,
    ],
    isNewArrival: true,
    isFeatured: true,
    sizes: ["16 inches", "18 inches", "20 inches"],
    purity: "22K (916 Gold)",
    sku: "LUX-GGN-02",
  },

  // 3. Pearl Drop Earrings
  {
    id: "prod-3",
    name: "Pearl Drop Earrings",
    subtitle: "South Sea Cultured Pearls & Diamond Clusters",
    description: "Suspended from delicate diamond-encrusted stems, these lustrous South Sea pearls emanate unmatched iridescence, perfectly balancing understated majesty with modern grace.",
    details: [
      "Genuine 11mm South Sea Cultured White Pearls",
      "0.45ct brilliant cut diamonds in 18K Yellow Gold",
      "Friction-back post with comfort disc backing",
      "Ethically farmed & certified gemological provenance",
    ],
    price: 88000,
    originalPrice: 98000,
    discountPercentage: 10,
    category: "gold",
    metal: "18K Yellow Gold",
    stone: "Pearl",
    stock: 8,
    rating: 4.7,
    reviewCount: 19,
    images: [
      IMAGE_ASSETS.newArrivals.pearlDropEarrings.url,
      IMAGE_ASSETS.shopProducts.goldHoopEarrings.url,
      IMAGE_ASSETS.shopProducts.rubyStudEarrings.url,
    ],
    isNewArrival: true,
    sizes: ["Standard"],
    purity: "18K (750 Gold)",
    sku: "LUX-PDE-03",
  },

  // 4. Temple Gold Necklace
  {
    id: "prod-4",
    name: "Temple Gold Necklace",
    subtitle: "Heritage Nakshi Work with Antique Patina",
    description: "An ode to sacred Indian architecture. Artisans hand-carve divine motifs into 22K gold, accented with vintage ruby cabochons and emerald droplets.",
    details: [
      "Master artisan handcrafted Nakshi antique relief",
      "22K Hallmarked Gold, approx 58 grams",
      "Natural Burma ruby beads and raw unheated emeralds",
      "Heritage collector certificate included",
    ],
    price: 395000,
    originalPrice: 440000,
    discountPercentage: 10,
    category: "traditional",
    metal: "22K Yellow Gold",
    stone: "Ruby",
    stock: 2,
    rating: 5.0,
    reviewCount: 14,
    images: [
      IMAGE_ASSETS.newArrivals.templeGoldNecklace.url,
      IMAGE_ASSETS.shopProducts.kundanChokerSet.url,
      IMAGE_ASSETS.craftedByHands.url,
    ],
    isNewArrival: true,
    isFeatured: true,
    sizes: ["Adjustable Dori"],
    purity: "22K (916 Gold)",
    sku: "LUX-TGN-04",
  },

  // 5. Diamond Solitaire Ring
  {
    id: "prod-5",
    name: "Diamond Solitaire Ring",
    subtitle: "Platinum Six-Prong Crown Setting",
    description: "The pinnacle of romance. A pristine 2.0-carat cushion brilliant diamond held in an elevated 950 Platinum crown, engineered for maximum light refraction.",
    details: [
      "2.00ct Triple Excellent Cut Diamond",
      "Solid 950 Platinum hallmarked mount",
      "GIA Diamond Dossier laser inscribed",
      "Complimentary lifetime resizing",
    ],
    price: 310000,
    originalPrice: 350000,
    discountPercentage: 11,
    category: "diamond",
    metal: "Platinum",
    stone: "Solitaire Diamond",
    stock: 4,
    rating: 4.9,
    reviewCount: 29,
    images: [
      IMAGE_ASSETS.shopProducts.diamondSolitaireRing.url,
      IMAGE_ASSETS.collections.diamond.url,
    ],
    isBestSeller: true,
    sizes: ["US 5", "US 6", "US 7", "US 8"],
    purity: "PT 950",
    sku: "LUX-DSR-05",
  },

  // 6. Gold Hoop Earrings
  {
    id: "prod-6",
    name: "Gold Hoop Earrings",
    subtitle: "18K Yellow Gold Fluted Creoles",
    description: "Everyday luxury redefined. Sculpted fluting captures ambient reflections, giving these feather-light hoops an arresting glow from every angle.",
    details: [
      "18K Yellow Gold with hollow tube comfort core",
      "Hinged snap-bar closure",
      "Diameter: 28mm, Thickness: 4mm",
      "Hypoallergenic and nickel-free",
    ],
    price: 49000,
    originalPrice: 55000,
    discountPercentage: 11,
    category: "gold",
    metal: "18K Yellow Gold",
    stone: "None",
    stock: 12,
    rating: 4.6,
    reviewCount: 41,
    images: [
      IMAGE_ASSETS.shopProducts.goldHoopEarrings.url,
      IMAGE_ASSETS.newArrivals.pearlDropEarrings.url,
    ],
    sizes: ["28mm"],
    purity: "18K (750 Gold)",
    sku: "LUX-GHE-06",
  },

  // 7. Emerald Drop Necklace
  {
    id: "prod-7",
    name: "Emerald Drop Necklace",
    subtitle: "Colombian Pear Emerald with Diamond Halo",
    description: "Deep jungle-green radiance. A rare 3.2ct pear-cut Colombian emerald hangs gracefully from an intricate pavé diamond chain in 18K white gold.",
    details: [
      "3.20 Carat Natural Zambian/Colombian Emerald",
      "0.85ct F-G / VS diamonds",
      "18K White Gold adjustable chain (16-18 inches)",
      "Accompanied by Gubelin / SSEF gemstone report",
    ],
    price: 275000,
    originalPrice: 320000,
    discountPercentage: 14,
    category: "diamond",
    metal: "18K White Gold",
    stone: "Emerald",
    stock: 2,
    rating: 4.9,
    reviewCount: 16,
    images: [
      IMAGE_ASSETS.shopProducts.emeraldDropNecklace.url,
      IMAGE_ASSETS.heroBackground.url,
    ],
    isFeatured: true,
    sizes: ["18 inches"],
    purity: "18K (750 Gold)",
    sku: "LUX-EDN-07",
  },

  // 8. Ruby Stud Earrings
  {
    id: "prod-8",
    name: "Ruby Stud Earrings",
    subtitle: "Pigeon Blood Rubies in 18K Rose Gold",
    description: "Intense crimson brilliance framed in warm rose gold. These unheated rubies are crowned with micro-prong halo diamonds for timeless drama.",
    details: [
      "1.80ct total weight Pigeon Blood Natural Rubies",
      "18K Rose Gold four-prong screw-back posts",
      "Hand-matched for color depth and symmetry",
    ],
    price: 92000,
    originalPrice: 105000,
    discountPercentage: 12,
    category: "gold",
    metal: "18K Rose Gold",
    stone: "Ruby",
    stock: 6,
    rating: 4.7,
    reviewCount: 18,
    images: [
      IMAGE_ASSETS.shopProducts.rubyStudEarrings.url,
      IMAGE_ASSETS.newArrivals.pearlDropEarrings.url,
    ],
    sizes: ["Standard"],
    purity: "18K (750 Gold)",
    sku: "LUX-RSE-08",
  },

  // 9. Floral Diamond Bracelet
  {
    id: "prod-9",
    name: "Floral Diamond Bracelet",
    subtitle: "18K Yellow Gold Petal Links with Pavé Setting",
    description: "Nature's majesty translated into high jewellery. Interlocking botanical motifs studded with 4.5 carats of brilliant cut diamonds embrace the wrist with silky comfort.",
    details: [
      "4.50ct Total Diamond Weight (VVS, E-F Color)",
      "18K Yellow Gold with dual safety catch box clasp",
      "Flexible link articulation for contoured wrist fit",
    ],
    price: 360000,
    originalPrice: 410000,
    discountPercentage: 12,
    category: "diamond",
    metal: "18K Yellow Gold",
    stone: "VVS Diamonds",
    stock: 3,
    rating: 5.0,
    reviewCount: 11,
    images: [
      IMAGE_ASSETS.shopProducts.floralDiamondBracelet.url,
      IMAGE_ASSETS.collections.gold.url,
    ],
    isBestSeller: true,
    sizes: ["6.5 inches", "7.0 inches"],
    purity: "18K (750 Gold)",
    sku: "LUX-FDB-09",
  },

  // 10. Kundan Choker Set
  {
    id: "prod-10",
    name: "Kundan Choker Set",
    subtitle: "Royal Mughal Jadau with Meenakari Reverse",
    description: "Fit for empresses. Uncut Polki diamonds set in 24K gold foil (Jadau technique) with exquisite enamel Meenakari detailing on the reverse and emerald bead clusters.",
    details: [
      "Traditional 24K Jadau setting on 22K gold base",
      "Handcrafted Meenakari enamel on reverse side",
      "Matching statement chandelier earrings included",
      "Silk tassel cord with adjustable gold zari bead",
    ],
    price: 520000,
    originalPrice: 580000,
    discountPercentage: 10,
    category: "bridal",
    metal: "22K Yellow Gold",
    stone: "Kundan",
    stock: 2,
    rating: 5.0,
    reviewCount: 27,
    images: [
      IMAGE_ASSETS.shopProducts.kundanChokerSet.url,
      IMAGE_ASSETS.collections.bridal.url,
      IMAGE_ASSETS.craftedByHands.url,
    ],
    isFeatured: true,
    isBestSeller: true,
    sizes: ["Free Size (Adjustable)"],
    purity: "22K (916 Gold)",
    sku: "LUX-KCS-10",
  },

  // 11. Eternal Solitaire Ring
  {
    id: "prod-11",
    name: "Eternal Solitaire Ring",
    description: "A classic solitaire diamond ring in 18K white gold with a brilliant-cut center stone.",
    price: 145000,
    discountPrice: 129999,
    category: "diamond",
    metal: "18K White Gold",
    stone: "Solitaire Diamond",
    stock: 6,
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 24,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 12. Halo Diamond Studs
  {
    id: "prod-12",
    name: "Halo Diamond Studs",
    description: "Round diamond stud earrings surrounded by a delicate halo of smaller diamonds.",
    price: 89999,
    discountPrice: 79999,
    category: "diamond",
    metal: "18K White Gold",
    stone: "VVS Diamonds",
    stock: 8,
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 18,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 13. Infinity Diamond Pendant
  {
    id: "prod-13",
    name: "Infinity Diamond Pendant",
    description: "An elegant infinity-shaped pendant with pavé-set diamonds on a fine gold chain.",
    price: 65000,
    discountPrice: 58500,
    category: "diamond",
    metal: "18K Yellow Gold",
    stone: "VVS Diamonds",
    stock: 10,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 15,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 14. Rose Gold Diamond Bangle
  {
    id: "prod-14",
    name: "Rose Gold Diamond Bangle",
    description: "A sleek rose gold bangle with channel-set diamonds, perfect for everyday luxury.",
    price: 210000,
    discountPrice: 189000,
    category: "diamond",
    metal: "18K Rose Gold",
    stone: "VVS Diamonds",
    stock: 4,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 21,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 15. Princess Cut Diamond Ring
  {
    id: "prod-15",
    name: "Princess Cut Diamond Ring",
    description: "A princess-cut diamond ring set in platinum with a double-prong setting.",
    price: 175000,
    discountPrice: 157500,
    category: "diamond",
    metal: "Platinum",
    stone: "Solitaire Diamond",
    stock: 5,
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 29,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 16. Diamond Tennis Bracelet
  {
    id: "prod-16",
    name: "Diamond Tennis Bracelet",
    description: "A timeless tennis bracelet featuring 52 round brilliant diamonds in white gold.",
    price: 350000,
    discountPrice: 315000,
    category: "diamond",
    metal: "18K White Gold",
    stone: "VVS Diamonds",
    stock: 3,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 5.0,
    reviewCount: 32,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 17. Pear Shape Diamond Drop Earrings
  {
    id: "prod-17",
    name: "Pear Shape Diamond Drop Earrings",
    description: "Pear-shaped diamond drop earrings with a delicate milgrain border.",
    price: 120000,
    discountPrice: 108000,
    category: "diamond",
    metal: "18K White Gold",
    stone: "Solitaire Diamond",
    stock: 7,
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 16,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 18. Diamond Cluster Cocktail Ring
  {
    id: "prod-18",
    name: "Diamond Cluster Cocktail Ring",
    description: "A statement cocktail ring with a cluster of diamonds in a floral motif.",
    price: 285000,
    discountPrice: 256500,
    category: "diamond",
    metal: "18K White Gold",
    stone: "VVS Diamonds",
    stock: 4,
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 22,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 19. Diamond Line Necklace
  {
    id: "prod-19",
    name: "Diamond Line Necklace",
    description: "A minimalist diamond line necklace with 40 round diamonds in 18K yellow gold.",
    price: 420000,
    discountPrice: 378000,
    category: "diamond",
    metal: "18K Yellow Gold",
    stone: "VVS Diamonds",
    stock: 2,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 5.0,
    reviewCount: 19,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 20. Diamond Eternity Band
  {
    id: "prod-20",
    name: "Diamond Eternity Band",
    description: "A full eternity band with emerald-cut diamonds, symbolizing everlasting love.",
    price: 195000,
    discountPrice: 175500,
    category: "diamond",
    metal: "Platinum",
    stone: "VVS Diamonds",
    stock: 5,
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 27,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 21. 22K Gold Temple Necklace
  {
    id: "prod-21",
    name: "22K Gold Temple Necklace",
    description: "A traditional temple-style gold necklace with intricate carvings of deities.",
    price: 380000,
    discountPrice: 342000,
    category: "gold",
    metal: "22K Yellow Gold",
    stone: "None",
    stock: 3,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 31,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 22. Gold Coin Pendant Necklace
  {
    id: "prod-22",
    name: "Gold Coin Pendant Necklace",
    description: "A 22K gold coin pendant on a fine gold chain, a symbol of prosperity.",
    price: 55000,
    discountPrice: 49500,
    category: "gold",
    metal: "22K Yellow Gold",
    stone: "None",
    stock: 12,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 14,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 23. Gold Jhumka Earrings
  {
    id: "prod-23",
    name: "Gold Jhumka Earrings",
    description: "Traditional gold jhumka earrings with pearl drops and filigree work.",
    price: 72000,
    discountPrice: 64800,
    category: "gold",
    metal: "22K Yellow Gold",
    stone: "Pearl",
    stock: 9,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 25,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 24. Gold Chain with Om Pendant
  {
    id: "prod-24",
    name: "Gold Chain with Om Pendant",
    description: "A gold chain with an Om pendant, perfect for daily wear and spiritual occasions.",
    price: 48000,
    discountPrice: 43200,
    category: "gold",
    metal: "22K Yellow Gold",
    stone: "None",
    stock: 15,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 36,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 25. Gold Kada Bangle Set
  {
    id: "prod-25",
    name: "Gold Kada Bangle Set",
    description: "A set of two 22K gold kada bangles with intricate engraved patterns.",
    price: 250000,
    discountPrice: 225000,
    category: "gold",
    metal: "22K Yellow Gold",
    stone: "None",
    stock: 4,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 5.0,
    reviewCount: 28,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 26. Gold Mangalsutra with Black Beads
  {
    id: "prod-26",
    name: "Gold Mangalsutra with Black Beads",
    description: "A modern gold mangalsutra with black beads and a diamond-studded pendant.",
    price: 95000,
    discountPrice: 85500,
    category: "gold",
    metal: "22K Yellow Gold",
    stone: "Solitaire Diamond",
    stock: 7,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 20,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 27. Gold Anklet Pair
  {
    id: "prod-27",
    name: "Gold Anklet Pair",
    description: "A pair of 22K gold anklets with small bells and chain links.",
    price: 38000,
    discountPrice: 34200,
    category: "gold",
    metal: "22K Yellow Gold",
    stone: "None",
    stock: 11,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 13,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 28. Gold Nose Pin
  {
    id: "prod-28",
    name: "Gold Nose Pin",
    description: "A delicate gold nose pin with a small diamond, perfect for everyday elegance.",
    price: 12500,
    discountPrice: 11250,
    category: "gold",
    metal: "22K Yellow Gold",
    stone: "Solitaire Diamond",
    stock: 20,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 42,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 29. Gold Ring with Ruby Stone
  {
    id: "prod-29",
    name: "Gold Ring with Ruby Stone",
    description: "A 22K gold ring featuring a deep red ruby stone in a bezel setting.",
    price: 85000,
    discountPrice: 76500,
    category: "gold",
    metal: "22K Yellow Gold",
    stone: "Ruby",
    stock: 6,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 17,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 30. Gold Layered Chain Necklace
  {
    id: "prod-30",
    name: "Gold Layered Chain Necklace",
    description: "A multi-layered gold chain necklace with a contemporary design.",
    price: 110000,
    discountPrice: 99000,
    category: "gold",
    metal: "22K Yellow Gold",
    stone: "None",
    stock: 8,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 23,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 31. Kundan Choker Set
  {
    id: "prod-31",
    name: "Kundan Choker Set",
    description: "A royal Kundan choker set with uncut diamonds, emeralds, and pearl drops.",
    price: 450000,
    discountPrice: 405000,
    category: "traditional",
    metal: "22K Yellow Gold",
    stone: "Kundan",
    stock: 3,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 5.0,
    reviewCount: 35,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 32. Polki Long Haram
  {
    id: "prod-32",
    name: "Polki Long Haram",
    description: "A long Polki haram necklace with layered chains and intricate gold work.",
    price: 580000,
    discountPrice: 522000,
    category: "traditional",
    metal: "22K Yellow Gold",
    stone: "Kundan",
    stock: 2,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 26,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 33. Meenakari Jhumka Earrings
  {
    id: "prod-33",
    name: "Meenakari Jhumka Earrings",
    description: "Traditional Meenakari jhumka earrings with colorful enamel work and pearl drops.",
    price: 68000,
    discountPrice: 61200,
    category: "traditional",
    metal: "22K Yellow Gold",
    stone: "Pearl",
    stock: 10,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 19,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 34. Temple Jewelry Maang Tikka
  {
    id: "prod-34",
    name: "Temple Jewelry Maang Tikka",
    description: "A temple-style maang tikka with Goddess Lakshmi motifs and gold beads.",
    price: 125000,
    discountPrice: 112500,
    category: "traditional",
    metal: "22K Yellow Gold",
    stone: "Kundan",
    stock: 5,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 21,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 35. Jadau Necklace Set
  {
    id: "prod-35",
    name: "Jadau Necklace Set",
    description: "An exquisite Jadau necklace set with precious stones and gold foil work.",
    price: 620000,
    discountPrice: 558000,
    category: "traditional",
    metal: "22K Yellow Gold",
    stone: "Kundan",
    stock: 2,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 5.0,
    reviewCount: 30,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 36. Antique Gold Choker
  {
    id: "prod-36",
    name: "Antique Gold Choker",
    description: "An antique-finish gold choker with intricate lattice patterns and ruby accents.",
    price: 320000,
    discountPrice: 288000,
    category: "traditional",
    metal: "22K Yellow Gold",
    stone: "Ruby",
    stock: 4,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 18,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 37. Traditional Bajubandh (Armlet)
  {
    id: "prod-37",
    name: "Traditional Bajubandh (Armlet)",
    description: "A traditional gold bajubandh with carved motifs and a central medallion.",
    price: 180000,
    discountPrice: 162000,
    category: "traditional",
    metal: "22K Yellow Gold",
    stone: "Kundan",
    stock: 5,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 14,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 38. Kamarbandh (Waist Chain)
  {
    id: "prod-38",
    name: "Kamarbandh (Waist Chain)",
    description: "A gold kamarbandh with delicate chain links and a central floral pendant.",
    price: 290000,
    discountPrice: 261000,
    category: "traditional",
    metal: "22K Yellow Gold",
    stone: "Kundan",
    stock: 3,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 22,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 39. Navratna Pendant Set
  {
    id: "prod-39",
    name: "Navratna Pendant Set",
    description: "A Navratna pendant with nine gemstones representing the nine planets.",
    price: 410000,
    discountPrice: 369000,
    category: "traditional",
    metal: "22K Yellow Gold",
    stone: "Ruby",
    stock: 4,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 5.0,
    reviewCount: 27,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 40. Traditional Gold Thushi Necklace
  {
    id: "prod-40",
    name: "Traditional Gold Thushi Necklace",
    description: "A Maharashtrian-style gold Thushi necklace with tight gold bead clusters.",
    price: 150000,
    discountPrice: 135000,
    category: "traditional",
    metal: "22K Yellow Gold",
    stone: "None",
    stock: 6,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 20,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 41. Bridal Polki Necklace Set
  {
    id: "prod-41",
    name: "Bridal Polki Necklace Set",
    description: "A complete bridal Polki necklace set with matching earrings and maang tikka.",
    price: 850000,
    discountPrice: 765000,
    category: "bridal",
    metal: "22K Yellow Gold",
    stone: "Kundan",
    stock: 2,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 5.0,
    reviewCount: 34,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 42. Bridal Diamond Choker
  {
    id: "prod-42",
    name: "Bridal Diamond Choker",
    description: "A stunning bridal diamond choker with emerald drops and pearl accents.",
    price: 720000,
    discountPrice: 648000,
    category: "bridal",
    metal: "18K White Gold",
    stone: "VVS Diamonds",
    stock: 2,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 28,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 43. Bridal Jhumka Set
  {
    id: "prod-43",
    name: "Bridal Jhumka Set",
    description: "A pair of large bridal jhumkas with pearl drops and gold filigree.",
    price: 380000,
    discountPrice: 342000,
    category: "bridal",
    metal: "22K Yellow Gold",
    stone: "Pearl",
    stock: 4,
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 22,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 44. Bridal Maang Tikka
  {
    id: "prod-44",
    name: "Bridal Maang Tikka",
    description: "A bridal maang tikka with a central diamond and pearl drops.",
    price: 250000,
    discountPrice: 225000,
    category: "bridal",
    metal: "22K Yellow Gold",
    stone: "Solitaire Diamond",
    stock: 5,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 19,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 45. Bridal Haath Phool
  {
    id: "prod-45",
    name: "Bridal Haath Phool",
    description: "A bridal haath phool with gold chains connecting to a floral ring.",
    price: 195000,
    discountPrice: 175500,
    category: "bridal",
    metal: "22K Yellow Gold",
    stone: "Kundan",
    stock: 6,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 16,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 46. Bridal Kundan Bangle Set
  {
    id: "prod-46",
    name: "Bridal Kundan Bangle Set",
    description: "A set of four Kundan bangles with red and green stone accents.",
    price: 460000,
    discountPrice: 414000,
    category: "bridal",
    metal: "22K Yellow Gold",
    stone: "Kundan",
    stock: 3,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 5.0,
    reviewCount: 31,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 47. Bridal Necklace with Earrings
  {
    id: "prod-47",
    name: "Bridal Necklace with Earrings",
    description: "A grand bridal necklace set with uncut diamonds, rubies, and emeralds.",
    price: 980000,
    discountPrice: 882000,
    category: "bridal",
    metal: "22K Yellow Gold",
    stone: "Emerald",
    stock: 2,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 5.0,
    reviewCount: 40,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 48. Bridal Nose Ring (Nath)
  {
    id: "prod-48",
    name: "Bridal Nose Ring (Nath)",
    description: "A traditional bridal nose ring with a delicate chain and pearl drop.",
    price: 85000,
    discountPrice: 76500,
    category: "bridal",
    metal: "22K Yellow Gold",
    stone: "Pearl",
    stock: 8,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 15,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 49. Bridal Payal (Anklet) Set
  {
    id: "prod-49",
    name: "Bridal Payal (Anklet) Set",
    description: "A heavy bridal payal set with silver bells and gold plating.",
    price: 140000,
    discountPrice: 126000,
    category: "bridal",
    metal: "22K Yellow Gold",
    stone: "None",
    stock: 5,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 17,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },

  // 50. Bridal Full Set (Necklace + Earrings + Tikka + Bangles)
  {
    id: "prod-50",
    name: "Bridal Full Set (Necklace + Earrings + Tikka + Bangles)",
    description: "A complete bridal jewellery set including necklace, earrings, maang tikka, and bangles.",
    price: 1250000,
    discountPrice: 1125000,
    category: "bridal",
    metal: "22K Yellow Gold",
    stone: "Kundan",
    stock: 1,
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 5.0,
    reviewCount: 45,
    isNewArrival: true,
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    userId: "usr-1",
    userName: "Devika Singhania",
    rating: 5,
    title: "Mesmerizing Craftsmanship",
    comment: "The Royal Bloom ring surpassed all expectations. The diamond fire in natural sunlight is breathtaking, and the bespoke wooden packaging made unboxing feel like a royal ceremony.",
    date: "12 September 2026",
    verifiedPurchase: true,
  },
  {
    id: "rev-2",
    userId: "usr-2",
    userName: "Aditya Roy Kapur",
    rating: 5,
    title: "Unmatched Heritage Elegance",
    comment: "Bought the Kundan Choker for our wedding anniversary. The Meenakari enamel work on the reverse is genuine museum-grade artistry. LUXORA is in a league of its own.",
    date: "04 August 2026",
    verifiedPurchase: true,
  },
  {
    id: "rev-3",
    userId: "usr-3",
    userName: "Aanya Verma",
    rating: 5,
    title: "Pure Perfection",
    comment: "I was hesitant to buy luxury high jewellery online, but LUXORA's certification, white-glove insured delivery, and flawless finish convinced me. Truly remarkable.",
    date: "28 July 2026",
    verifiedPurchase: true,
  },
];
