import { Product, Collection, Review } from "@/types";
import { IMAGE_ASSETS } from "./imageAssets";

export const COLLECTIONS: Collection[] = [
  {
    id: "col-diamond",
    title: "Diamond",
    category: "diamond",
    image: IMAGE_ASSETS.collections.diamond.url,
    alt: IMAGE_ASSETS.collections.diamond.alt,
    description: "Brilliance in every facet. Solitaires, baguettes, and fine pavé settings.",
    itemCount: 24,
  },
  {
    id: "col-gold",
    title: "Gold",
    category: "gold",
    image: IMAGE_ASSETS.collections.gold.url,
    alt: IMAGE_ASSETS.collections.gold.alt,
    description: "Solid 18K and 22K gold heirlooms, sculptured with everlasting warmth.",
    itemCount: 38,
  },
  {
    id: "col-silver",
    title: "Silver",
    category: "silver",
    image: IMAGE_ASSETS.collections.silver.url,
    alt: IMAGE_ASSETS.collections.silver.alt,
    description: "925 sterling silver minimalist luxury for modern silhouettes.",
    itemCount: 19,
  },
  {
    id: "col-traditional",
    title: "Traditional",
    category: "traditional",
    image: IMAGE_ASSETS.collections.traditional.url,
    alt: IMAGE_ASSETS.collections.traditional.alt,
    description: "Royal Jadau, Polki, and antique temple ornaments steeped in culture.",
    itemCount: 32,
  },
  {
    id: "col-bridal",
    title: "Bridal",
    category: "bridal",
    image: IMAGE_ASSETS.collections.bridal.url,
    alt: IMAGE_ASSETS.collections.bridal.alt,
    description: "Bespoke bridal suites for life's most unforgettable milestone.",
    itemCount: 15,
  },
];

export const PRODUCTS: Product[] = [
  // 1. Royal Bloom Diamond Ring (Featured & New Arrival)
  {
    id: "prod-1",
    name: "Royal Bloom Diamond Ring",
    subtitle: "18K White Gold Solitaire with Pavé Halo",
    description: "A testament to celestial craftsmanship. The Royal Bloom Diamond Ring features a hand-selected 1.50ct round brilliant centre diamond embraced by a shimmering pavé halo on an 18K white gold micro-set band.",
    details: [
      "Certified IGI / GIA Natural Diamond",
      "1.50 Carat Centre Stone (VVS1 Clarity, E Color)",
      "Band crafted in Hallmarked 18K White Gold",
      "Complimentary laser engraving & luxury presentation chest",
      "Lifetime cleaning & inspection guarantee",
    ],
    price: 185000,
    originalPrice: 215000,
    discountPercentage: 14,
    category: "diamond",
    metal: "18K White Gold",
    stone: "Solitaire Diamond",
    stock: 5,
    rating: 4.9,
    reviewCount: 38,
    images: [
      IMAGE_ASSETS.newArrivals.royalBloomDiamondRing.url,
      IMAGE_ASSETS.productDetailMain.url,
      IMAGE_ASSETS.collections.diamond.url,
    ],
    isNewArrival: true,
    isFeatured: true,
    isBestSeller: true,
    sizes: ["US 5", "US 6", "US 7", "US 8", "US 9"],
    purity: "18K (750 Gold)",
    sku: "LUX-RBD-01",
  },

  // 2. Golden Grace Necklace
  {
    id: "prod-2",
    name: "Golden Grace Necklace",
    subtitle: "22K Sculpted Yellow Gold Collar Chain",
    description: "Fluid geometry in warm 22K yellow gold. Inspired by timeless Byzantine link architecture, this necklace drapes like liquid light against the collarbone.",
    details: [
      "Hallmarked 22K (916) Pure Yellow Gold",
      "Net Weight: 34.5 grams",
      "Secure custom toggle clasp with safety lock",
      "Hand-polished mirror and satin contrast finish",
    ],
    price: 245000,
    originalPrice: 270000,
    discountPercentage: 9,
    category: "gold",
    metal: "22K Yellow Gold",
    stone: "None",
    stock: 3,
    rating: 4.8,
    reviewCount: 22,
    images: [
      IMAGE_ASSETS.newArrivals.goldenGraceNecklace.url,
      IMAGE_ASSETS.collections.gold.url,
      IMAGE_ASSETS.shopProducts.floralDiamondBracelet.url,
    ],
    isNewArrival: true,
    isFeatured: true,
    sizes: ["16 inches", "18 inches", "20 inches"],
    purity: "22K (916 Gold)",
    sku: "LUX-GGN-02",
  },

  // 3. Pearl Drop Earrings
  {
    id: "prod-3",
    name: "Pearl Drop Earrings",
    subtitle: "South Sea Cultured Pearls & Diamond Clusters",
    description: "Suspended from delicate diamond-encrusted stems, these lustrous South Sea pearls emanate unmatched iridescence, perfectly balancing understated majesty with modern grace.",
    details: [
      "Genuine 11mm South Sea Cultured White Pearls",
      "0.45ct brilliant cut diamonds in 18K Yellow Gold",
      "Friction-back post with comfort disc backing",
      "Ethically farmed & certified gemological provenance",
    ],
    price: 88000,
    originalPrice: 98000,
    discountPercentage: 10,
    category: "gold",
    metal: "18K Yellow Gold",
    stone: "Pearl",
    stock: 8,
    rating: 4.7,
    reviewCount: 19,
    images: [
      IMAGE_ASSETS.newArrivals.pearlDropEarrings.url,
      IMAGE_ASSETS.shopProducts.goldHoopEarrings.url,
      IMAGE_ASSETS.shopProducts.rubyStudEarrings.url,
    ],
    isNewArrival: true,
    sizes: ["Standard"],
    purity: "18K (750 Gold)",
    sku: "LUX-PDE-03",
  },

  // 4. Temple Gold Necklace
  {
    id: "prod-4",
    name: "Temple Gold Necklace",
    subtitle: "Heritage Nakshi Work with Antique Patina",
    description: "An ode to sacred Indian architecture. Artisans hand-carve divine motifs into 22K gold, accented with vintage ruby cabochons and emerald droplets.",
    details: [
      "Master artisan handcrafted Nakshi antique relief",
      "22K Hallmarked Gold, approx 58 grams",
      "Natural Burma ruby beads and raw unheated emeralds",
      "Heritage collector certificate included",
    ],
    price: 395000,
    originalPrice: 440000,
    discountPercentage: 10,
    category: "traditional",
    metal: "22K Yellow Gold",
    stone: "Ruby",
    stock: 2,
    rating: 5.0,
    reviewCount: 14,
    images: [
      IMAGE_ASSETS.newArrivals.templeGoldNecklace.url,
      IMAGE_ASSETS.shopProducts.kundanChokerSet.url,
      IMAGE_ASSETS.craftedByHands.url,
    ],
    isNewArrival: true,
    isFeatured: true,
    sizes: ["Adjustable Dori"],
    purity: "22K (916 Gold)",
    sku: "LUX-TGN-04",
  },

  // 5. Diamond Solitaire Ring
  {
    id: "prod-5",
    name: "Diamond Solitaire Ring",
    subtitle: "Platinum Six-Prong Crown Setting",
    description: "The pinnacle of romance. A pristine 2.0-carat cushion brilliant diamond held in an elevated 950 Platinum crown, engineered for maximum light refraction.",
    details: [
      "2.00ct Triple Excellent Cut Diamond",
      "Solid 950 Platinum hallmarked mount",
      "GIA Diamond Dossier laser inscribed",
      "Complimentary lifetime resizing",
    ],
    price: 310000,
    originalPrice: 350000,
    discountPercentage: 11,
    category: "diamond",
    metal: "Platinum",
    stone: "Solitaire Diamond",
    stock: 4,
    rating: 4.9,
    reviewCount: 29,
    images: [
      IMAGE_ASSETS.shopProducts.diamondSolitaireRing.url,
      IMAGE_ASSETS.collections.diamond.url,
    ],
    isBestSeller: true,
    sizes: ["US 5", "US 6", "US 7", "US 8"],
    purity: "PT 950",
    sku: "LUX-DSR-05",
  },

  // 6. Gold Hoop Earrings
  {
    id: "prod-6",
    name: "Gold Hoop Earrings",
    subtitle: "18K Yellow Gold Fluted Creoles",
    description: "Everyday luxury redefined. Sculpted fluting captures ambient reflections, giving these feather-light hoops an arresting glow from every angle.",
    details: [
      "18K Yellow Gold with hollow tube comfort core",
      "Hinged snap-bar closure",
      "Diameter: 28mm, Thickness: 4mm",
      "Hypoallergenic and nickel-free",
    ],
    price: 49000,
    originalPrice: 55000,
    discountPercentage: 11,
    category: "gold",
    metal: "18K Yellow Gold",
    stone: "None",
    stock: 12,
    rating: 4.6,
    reviewCount: 41,
    images: [
      IMAGE_ASSETS.shopProducts.goldHoopEarrings.url,
      IMAGE_ASSETS.newArrivals.pearlDropEarrings.url,
    ],
    sizes: ["28mm"],
    purity: "18K (750 Gold)",
    sku: "LUX-GHE-06",
  },

  // 7. Emerald Drop Necklace
  {
    id: "prod-7",
    name: "Emerald Drop Necklace",
    subtitle: "Colombian Pear Emerald with Diamond Halo",
    description: "Deep jungle-green radiance. A rare 3.2ct pear-cut Colombian emerald hangs gracefully from an intricate pavé diamond chain in 18K white gold.",
    details: [
      "3.20 Carat Natural Zambian/Colombian Emerald",
      "0.85ct F-G / VS diamonds",
      "18K White Gold adjustable chain (16-18 inches)",
      "Accompanied by Gubelin / SSEF gemstone report",
    ],
    price: 275000,
    originalPrice: 320000,
    discountPercentage: 14,
    category: "diamond",
    metal: "18K White Gold",
    stone: "Emerald",
    stock: 2,
    rating: 4.9,
    reviewCount: 16,
    images: [
      IMAGE_ASSETS.shopProducts.emeraldDropNecklace.url,
      IMAGE_ASSETS.heroBackground.url,
    ],
    isFeatured: true,
    sizes: ["18 inches"],
    purity: "18K (750 Gold)",
    sku: "LUX-EDN-07",
  },

  // 8. Ruby Stud Earrings
  {
    id: "prod-8",
    name: "Ruby Stud Earrings",
    subtitle: "Pigeon Blood Rubies in 18K Rose Gold",
    description: "Intense crimson brilliance framed in warm rose gold. These unheated rubies are crowned with micro-prong halo diamonds for timeless drama.",
    details: [
      "1.80ct total weight Pigeon Blood Natural Rubies",
      "18K Rose Gold four-prong screw-back posts",
      "Hand-matched for color depth and symmetry",
    ],
    price: 92000,
    originalPrice: 105000,
    discountPercentage: 12,
    category: "gold",
    metal: "18K Rose Gold",
    stone: "Ruby",
    stock: 6,
    rating: 4.7,
    reviewCount: 18,
    images: [
      IMAGE_ASSETS.shopProducts.rubyStudEarrings.url,
      IMAGE_ASSETS.newArrivals.pearlDropEarrings.url,
    ],
    sizes: ["Standard"],
    purity: "18K (750 Gold)",
    sku: "LUX-RSE-08",
  },

  // 9. Floral Diamond Bracelet
  {
    id: "prod-9",
    name: "Floral Diamond Bracelet",
    subtitle: "18K Yellow Gold Petal Links with Pavé Setting",
    description: "Nature's majesty translated into high jewellery. Interlocking botanical motifs studded with 4.5 carats of brilliant cut diamonds embrace the wrist with silky comfort.",
    details: [
      "4.50ct Total Diamond Weight (VVS, E-F Color)",
      "18K Yellow Gold with dual safety catch box clasp",
      "Flexible link articulation for contoured wrist fit",
    ],
    price: 360000,
    originalPrice: 410000,
    discountPercentage: 12,
    category: "diamond",
    metal: "18K Yellow Gold",
    stone: "VVS Diamonds",
    stock: 3,
    rating: 5.0,
    reviewCount: 11,
    images: [
      IMAGE_ASSETS.shopProducts.floralDiamondBracelet.url,
      IMAGE_ASSETS.collections.gold.url,
    ],
    isBestSeller: true,
    sizes: ["6.5 inches", "7.0 inches"],
    purity: "18K (750 Gold)",
    sku: "LUX-FDB-09",
  },

  // 10. Kundan Choker Set
  {
    id: "prod-10",
    name: "Kundan Choker Set",
    subtitle: "Royal Mughal Jadau with Meenakari Reverse",
    description: "Fit for empresses. Uncut Polki diamonds set in 24K gold foil (Jadau technique) with exquisite enamel Meenakari detailing on the reverse and emerald bead clusters.",
    details: [
      "Traditional 24K Jadau setting on 22K gold base",
      "Handcrafted Meenakari enamel on reverse side",
      "Matching statement chandelier earrings included",
      "Silk tassel cord with adjustable gold zari bead",
    ],
    price: 520000,
    originalPrice: 580000,
    discountPercentage: 10,
    category: "bridal",
    metal: "22K Yellow Gold",
    stone: "Kundan",
    stock: 2,
    rating: 5.0,
    reviewCount: 27,
    images: [
      IMAGE_ASSETS.shopProducts.kundanChokerSet.url,
      IMAGE_ASSETS.collections.bridal.url,
      IMAGE_ASSETS.craftedByHands.url,
    ],
    isFeatured: true,
    isBestSeller: true,
    sizes: ["Free Size (Adjustable)"],
    purity: "22K (916 Gold)",
    sku: "LUX-KCS-10",
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    userId: "usr-1",
    userName: "Devika Singhania",
    rating: 5,
    title: "Mesmerizing Craftsmanship",
    comment: "The Royal Bloom ring surpassed all expectations. The diamond fire in natural sunlight is breathtaking, and the bespoke wooden packaging made unboxing feel like a royal ceremony.",
    date: "12 September 2026",
    verifiedPurchase: true,
  },
  {
    id: "rev-2",
    userId: "usr-2",
    userName: "Aditya Roy Kapur",
    rating: 5,
    title: "Unmatched Heritage Elegance",
    comment: "Bought the Kundan Choker for our wedding anniversary. The Meenakari enamel work on the reverse is genuine museum-grade artistry. LUXORA is in a league of its own.",
    date: "04 August 2026",
    verifiedPurchase: true,
  },
  {
    id: "rev-3",
    userId: "usr-3",
    userName: "Aanya Verma",
    rating: 5,
    title: "Pure Perfection",
    comment: "I was hesitant to buy luxury high jewellery online, but LUXORA's certification, white-glove insured delivery, and flawless finish convinced me. Truly remarkable.",
    date: "28 July 2026",
    verifiedPurchase: true,
  },
];
